### ISSUE TITLE
Property 'nodeCookie' does not exist on type 'NuxtCookies'

### ISSUE THREAD

**Issue by doantu05150** [microcipcip/cookie-universal#131]
I tried to write this line ` const parsed = this.$cookies.nodeCookie.parse(cookies)` but getting error `Property 'nodeCookie' does not exist on type 'NuxtCookies'`
I check the definition [type](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal-nuxt/types/index.d.ts) file and no nodeCookie property found?
Does anyone know what I am doing wrong?

**Comment by microcipcip** [comment]
Yeah I think the type definition is incomplete, is missing the `nodeCookie` so you can't reach it with typescript even if the method is indeed there.

**Comment by stephenjason89** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3810177/183011000-4a2834f5-9bc0-4650-b61d-2dceb253e36b.png">
<img width="554" alt="image" src="https://user-images.githubusercontent.com/3810177/183011038-016edbd9-844e-452d-91c0-f70563c36ae3.png">

Hello @microcipcip 
I'm experiencing the same issue.

**Comment by microcipcip** [comment]
Ok, I'll try patch the ts definitions, a PR is also accepted.

**Comment by stephenjason89** [comment]
I'll make a PR for it :D

**Comment by microcipcip** [comment]
The PR is merged and I've also copied over PR #135 code for the ts definitions of cookie-universal-nuxt. I've also published a new version of the package (v2.2.2). Let me know if ts definitions now works. Thanks for the PR!

**Comment by stephenjason89** [comment]
@microcipcip Everything is working fine on my end using v2.2.2.
Thank you!

**Comment by microcipcip** [comment]
Amazing!
